# Lista de Prospects Seed para Teste (PMEs Canadenses B2B)

prospects_seed = [
    {"company_name": "TechFlow Solutions", "domain": "techflow.ca", "contact_email": "ceo@techflow.ca"},
    {"company_name": "MapleLeaf Consulting", "domain": "mapleleaf-consulting.com", "contact_email": "info@mapleleaf-consulting.com"},
    {"company_name": "Northern Digital Agency", "domain": "northerndigital.ca", "contact_email": "hello@northerndigital.ca"},
    {"company_name": "Vancouver Marketing Co", "domain": "vanmarketing.ca", "contact_email": "contact@vanmarketing.ca"},
    {"company_name": "Calgary Business Solutions", "domain": "calgarybiz.ca", "contact_email": "info@calgarybiz.ca"},
    {"company_name": "Toronto Web Experts", "domain": "torontoweb.ca", "contact_email": "team@torontoweb.ca"},
    {"company_name": "Atlantic Design Group", "domain": "atlanticdesign.ca", "contact_email": "hello@atlanticdesign.ca"},
    {"company_name": "Prairie Digital", "domain": "prairiedigital.ca", "contact_email": "contact@prairiedigital.ca"},
    {"company_name": "Rockies Tech", "domain": "rockiestech.ca", "contact_email": "info@rockiestech.ca"},
    {"company_name": "GTA Solutions", "domain": "gtasolutions.ca", "contact_email": "sales@gtasolutions.ca"},
    {"company_name": "Quebec Innovations", "domain": "quebecinnov.ca", "contact_email": "contact@quebecinnov.ca"},
    {"company_name": "Maritime Consulting", "domain": "maritimeconsult.ca", "contact_email": "info@maritimeconsult.ca"},
    {"company_name": "Ontario Business Group", "domain": "ontariobiz.ca", "contact_email": "hello@ontariobiz.ca"},
    {"company_name": "BC Tech Solutions", "domain": "bctech.ca", "contact_email": "team@bctech.ca"},
    {"company_name": "Alberta Digital", "domain": "albertadigital.ca", "contact_email": "contact@albertadigital.ca"},
    {"company_name": "Saskatchewan Web", "domain": "saskweb.ca", "contact_email": "info@saskweb.ca"},
    {"company_name": "Manitoba Solutions", "domain": "manitobasol.ca", "contact_email": "sales@manitobasol.ca"},
    {"company_name": "Yukon Digital", "domain": "yukondigital.ca", "contact_email": "hello@yukondigital.ca"},
    {"company_name": "NWT Business", "domain": "nwtbusiness.ca", "contact_email": "contact@nwtbusiness.ca"},
    {"company_name": "PEI Consulting", "domain": "peiconsult.ca", "contact_email": "info@peiconsult.ca"},
    {"company_name": "Nova Scotia Tech", "domain": "nstech.ca", "contact_email": "team@nstech.ca"},
    {"company_name": "New Brunswick Digital", "domain": "nbdigital.ca", "contact_email": "hello@nbdigital.ca"},
    {"company_name": "Newfoundland Solutions", "domain": "nlsolutions.ca", "contact_email": "contact@nlsolutions.ca"},
    {"company_name": "Fraser Valley Tech", "domain": "fvtech.ca", "contact_email": "info@fvtech.ca"},
    {"company_name": "Okanagan Digital", "domain": "okanagandigital.ca", "contact_email": "sales@okanagandigital.ca"},
    {"company_name": "Niagara Business", "domain": "niagarabiz.ca", "contact_email": "hello@niagarabiz.ca"},
    {"company_name": "Muskoka Solutions", "domain": "muskokasol.ca", "contact_email": "team@muskokasol.ca"},
    {"company_name": "Algoma Tech", "domain": "algomatech.ca", "contact_email": "contact@algomatech.ca"},
    {"company_name": "Saguenay Digital", "domain": "saguenaydigital.ca", "contact_email": "info@saguenaydigital.ca"},
    {"company_name": "Outaouais Web", "domain": "outaouaisweb.ca", "contact_email": "hello@outaouaisweb.ca"},
    {"company_name": "Laurentians Tech", "domain": "laurentianstech.ca", "contact_email": "contact@laurentianstech.ca"},
    {"company_name": "Eastern Townships Digital", "domain": "etdigital.ca", "contact_email": "info@etdigital.ca"},
    {"company_name": "Gaspé Solutions", "domain": "gaspesol.ca", "contact_email": "team@gaspesol.ca"},
    {"company_name": "Côte-Nord Business", "domain": "cotenordbiz.ca", "contact_email": "sales@cotenordbiz.ca"},
    {"company_name": "Abitibi Tech", "domain": "abitibitech.ca", "contact_email": "hello@abitibitech.ca"},
    {"company_name": "Témiscamingue Digital", "domain": "temiscaminguedigital.ca", "contact_email": "contact@temiscaminguedigital.ca"},
    {"company_name": "Mauricie Web", "domain": "mauricieweb.ca", "contact_email": "info@mauricieweb.ca"},
    {"company_name": "Centre-du-Québec Solutions", "domain": "cdqsol.ca", "contact_email": "team@cdqsol.ca"},
    {"company_name": "Chaudière-Appalaches Tech", "domain": "chatech.ca", "contact_email": "hello@chatech.ca"},
    {"company_name": "Bas-Saint-Laurent Digital", "domain": "bsldigital.ca", "contact_email": "contact@bsldigital.ca"},
    {"company_name": "Lanaudière Business", "domain": "lanaudierebiz.ca", "contact_email": "info@lanaudierebiz.ca"},
    {"company_name": "Laurentides Web", "domain": "laurentidesweb.ca", "contact_email": "sales@laurentidesweb.ca"},
    {"company_name": "Montérégie Solutions", "domain": "monteregiesol.ca", "contact_email": "team@monteregiesol.ca"},
    {"company_name": "Laval Tech", "domain": "lavaltech.ca", "contact_email": "hello@lavaltech.ca"},
    {"company_name": "Longueuil Digital", "domain": "longueildigital.ca", "contact_email": "contact@longueildigital.ca"},
    {"company_name": "Sherbrooke Business", "domain": "sherbrookebiz.ca", "contact_email": "info@sherbrookebiz.ca"},
    {"company_name": "Trois-Rivières Web", "domain": "trweb.ca", "contact_email": "team@trweb.ca"},
    {"company_name": "Chicoutimi Solutions", "domain": "chicoutimisol.ca", "contact_email": "hello@chicoutimisol.ca"},
    {"company_name": "Rimouski Tech", "domain": "rimouskitech.ca", "contact_email": "contact@rimouskitech.ca"},
    {"company_name": "Rouyn-Noranda Digital", "domain": "rndigital.ca", "contact_email": "info@rndigital.ca"}
]
